name: github_view
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  auto_route: ^3.2.2
  cached_network_image: ^3.2.0
  dartz: ^0.10.1
  dio: ^4.0.4
  flash: ^2.0.3+2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2
  flutter_secure_storage: ^5.0.2
  freezed_annotation: ^1.1.0
  hooks_riverpod: ^1.0.3
  json_annotation: ^4.4.0
  material_design_icons_flutter: ^5.0.6595
  material_floating_search_bar: ^0.3.6
  oauth2: ^2.0.0
  path: ^1.8.1
  path_provider: ^2.0.8
  sembast: ^3.1.2
  shimmer: ^2.0.0
  webview_flutter: ^3.0.0

dev_dependencies:
  auto_route_generator: ^3.2.1
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  # flutter_test:
  #   sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
